### PR TITLE
Make readme

### PR DESCRIPTION
**Pull request by ericpre**
Prototype to make the readme automatically. This approach is based on:
- keep the logic in hyperspy to obtain the required information 
- run a script to update the `README.md` from a python environment to avoid interfering from the developer environment. This environment will contains only the libraries defined in `extension_list.txt`.
- the extension needs to be available on pypi and optionally on conda-forge

Once we agree on this approach, I can add more detailed information and improve the structure of the `README.md`

Future improvement:
- check for signal specifications conflicts (https://github.com/hyperspy/hyperspy/pull/2445)
- use markdown instead of html (the development version of prettytable support markdown https://github.com/jazzband/prettytable/blob/master/CHANGELOG.md)
- store information in this repository which could in turn be used by hyperspy?

### CODE REVIEW

**Comment by dnjohnstone** [comment]
Awesome! This looks really good to me.

I think this addresses concerns that @francisco-dlp raised in #2 ?

There are some things that this makes me think about:

1. How will we deal with the implicit requirement unique signal_type names? I know we've discussed this before and I think the initial problem we saw with pyxem and other packages has been addressed by working with @CSSFrancis and @magnunor to put empyer and pixstem functionality into pyxem and create one larger package. But it's bound to happen again in future...

2. What about model components? It seems a similar table could be generated easily and pyxem has some of those in there for testing this.

3. Do we need to agree on snake case vs. camel case for signal_type? It seems that KikuchiPy and pyxem are inconsistent on this, as is DielectricFunction. @hakonanes should probably be included in that.

4. In terms of sorting the table - I personally think it would be best if it were sorted alphabetically by the package column.

**Comment by hakonanes** [comment]
>     3. Do we need/want to agree on snake case vs. camel case for signal_type? It seems that we're inconsistent on this. @hakonanes should probably be included in that conversation.

I have no opinion on which case to use for signal_type, and will happily update kikuchipy signals's signal_type to whatever you find best.

**Comment by ericpre** [comment]
Thanks for your comments. This PR is about how we make the readme automatically, so it doesn't cover convention about `signal_type` and name clashes. Similarly, adding other gui widgets or model components should be done in another PR by adding the logic to obtain the information in hyperspy and not here.

**Comment by ericpre** [comment]
@francisco-dlp, to follow up on your comments (in https://github.com/hyperspy/hyperspy-extensions-list/pull/2#issuecomment-651619263):

> @ericpre, which are your current thoughts on how to implement this?
> 
> Some ideas that come to my mind in case that they can be useful:
> 
> * The list of extensions could be kept in json format
> * The `hs.print_known_signal_types()` function could optionally use the functionality implemented here to print the known signal types of packages that are not installed locally. Therefore, it would be good to have a clean API for external consumption.

I think this approach is simple and we would advice users to read this readme on github (as mentioned in https://github.com/hyperspy/hyperspy/pull/2434) to find more `signal_type` in case they are not available in their current environment.

**Comment by francisco-dlp** [comment]
This is a great improvement over the previous situation and I am happy to merge it as-is. I'll discuss some possible improvements in case that they can be useful for this PR or a future one.

In my mind, the main drawbacks of this PR are:

1. to add an extension one needs to create a conda environment with all the extensions listed
2. the items in the first table are added by hand
3. adding an extension requires making a fork of the repository, running code in a computer and sending a PR. The ideal solution would be one that simply by adding the name of the project in pypi to the list of extensions generates the list automatically using CI. 

Here are some ideas on how to achieve this:

1. Use [pypi's json API](https://warehouse.readthedocs.io/api-reference/json/) to get all the required info to populate the table and to download the package's tar.gz file
2. download the package's tar.gz file, extract the ``hyperspy_extension.yaml`` file and parse it to populate the second table. Eventually, the ``hyperspy_extension.yaml`` parsing code in hyperspy could be moved here. Therefore, the code here will become a hyperspy dependency.
3. Automatically generate all the tables currently in the README file, and automatically publish them, maybe simply using RtDs.
4. This package could be used by hyperspy to tell users which packages they need to install in order to get the right classes for their data.

**Comment by ericpre** [comment]
Yes, this is room for improvement in term of what we information we put here and how we reuse this information.

There is one point which is a bit ill defined: if the extension is not distributed on conda-forge the conda approach can't be used, however, this could be used as a reminder to package of this extension on conda-forge and an incentive for us to point the extension developer to do it or give a hand doing it!

Regarding the automation, I am not too concern about it at the moment, because we only expect to run it once a while, maybe once a month, run a few lines in a terminal locally, it should be OK.

> 1. Use [pypi's json API](https://warehouse.readthedocs.io/api-reference/json/) to get all the required info to populate the table and to download the package's tar.gz file
> 2. download the package's tar.gz file, extract the `hyperspy_extension.yaml` file and parse it to populate the second table. Eventually, the `hyperspy_extension.yaml` parsing code in hyperspy could be moved here. Therefore, the code here will become a hyperspy dependency.

For this two points, I find it actually very simple to keep the logic hyperspy and use the same functionalities as we would used otherwise. Some of the current steps could be put in scripts (one for the virtual environment approach and one for the conda environment)

> 3. Automatically generate all the tables currently in the README file, and automatically publish them, maybe simply using RtDs.

Yes, this can be done easily with github page and add it to the hyperspy website, similarly as it is done with the doc of hyperspyUI

> 4. This package could be used by hyperspy to tell users which packages they need to install in order to get the right classes for their data.

Yes, in the mean time before point 3. is done, we can point to this repository.

**Comment by dnjohnstone** [comment]
> There is one point which is a bit ill defined: if the extension is not distributed on conda-forge the conda approach can't be used, however, this could be used as a reminder to package of this extension on conda-forge and an incentive for us to point the extension developer to do it or give a hand doing it!

I think this is probably ok, maybe even good. Getting things on to conda-forge was a useful milestone for us in terms of development and it seems like a reasonable thing to ask for before including something in this list to me.

**Comment by francisco-dlp** [comment]
See https://github.com/ericpre/hyperspy-extensions-list/pull/1 for some small suggestions. The main one is giving the option to open an issue with a request to include a package.

**Pull request merged**
