### PR TITLE
Add lumispy

### PR DESCRIPTION
**Pull request by jlaehne**
With LumiSpy out on PyPi (https://pypi.python.org/pypi/lumispy), I think we can add it to the extensions list.

### CODE REVIEW

**Comment by ericpre** [comment]
Indeed, can you also run the script to update the readme file, as per instructions in https://github.com/hyperspy/hyperspy-extensions-list/blob/master/doc/how_to_add_extension.md?
Finger crossed that the script is working! :D

And also fix the link to the instructions while you are at it... it is broken because it was pointing to the branch of the pull request... it will most likely break again when we rename the `master` to the `main`! I don't know what are current github plan with this respect.

**Comment by jlaehne** [comment]
Already working on running the script ;-)

**Comment by jlaehne** [comment]
Should be ready.

**Comment by ericpre** [comment]
Some CI builds are failing because lumispy needs to be on conda-forge.

**Comment by jlaehne** [comment]
Though, some builds were failing in the Hyperspy-Test-Suite (on the protochips io tests) even before I added the lumispy tests.

**Comment by ericpre** [comment]
> Though, some builds were failing in the Hyperspy-Test-Suite (on the protochips io tests) even before I added the lumispy tests.

Yes, this is fixed in the development branches but it is not release yet and only the two first build should failed - see https://github.com/hyperspy/hyperspy-extensions-list/actions/runs/694017670

**Comment by jlaehne** [comment]
There are still more than two tests failing, but those are related to `kikuchipy` and not `lumispy`.

In fact, those are related to the new `is_binned` attribute of the axis dictionary (https://github.com/pyxem/kikuchipy/issues/326) and should be easy to fix.

**Comment by ericpre** [comment]
> There are still more than two tests failing, but those are related to `kikuchipy` and not `lumispy`.
> 
> In fact, those are related to the new `is_binned` attribute of the axis dictionary ([pyxem/kikuchipy#326](https://github.com/pyxem/kikuchipy/issues/326)) and should be easy to fix.

Yes, thanks for opening the issue. Beside that, it shows that this integration test suite is useful! :)

**Pull request merged**
